moler/cmd/unix/bash.py
=> comment changed

moler/cmd/commandtextualgeneric.py
=> Use six lib instead of checking python version with sys

moler/config/loggers.py, moler/connection.py, moler/util/__init__.py, moler/util/cmds_doc.py, test/conftest.py, test/test_cmds_doc.py
* Main tasks:
* clean up
* move to moler package
* add unit tests
* Subtasks:
* fix logger for RAW_DATA
* handling unicode / ascii correctly by logger
=> Test for commands documentation

moler/device/textualdevice.py, moler/exceptions.py, moler/util/moler_test.py
=> 71 exception traceback

moler/cmd/unix/ip_addr.py
=> fix bugs 76, add self.ret_required = False

moler/device/state_machine.py, moler/helpers.py, moler/scheduler.py, requirements.txt, test/test_scheduler.py
=> 62 scheduler callback

moler/cmd/unix/netstat.py
Implementation of netstat command
=> Cmd netstat

moler/cmd/unix/ssh.py, moler/cmd/unix/telnet.py
Added support for optional newline char(s) after prompt in ssh.
=> added support for optional newline char(s) after prompt

moler/cmd/unix/ps.py
=> Ps cmd refacotring

moler/cmd/unix/cp.py, moler/cmd/unix/ls.py, test/unix/test_cmd_ls.py
=> Ls cmd test fix

moler/cmd/__init__.py, moler/cmd/commandtextualgeneric.py, moler/cmd/unix/cd.py, moler/cmd/unix/ip_route.py, moler/cmd/unix/mpstat.py, test/test_helpers.py, test/unix/test_cmd_iproute.py, test/unix/test_cmd_mpstat.py
Improvements tests and refactoring Unix commands to reach 100% code coverage,
=> Coverage improvement

moler/util/moler_test.py, test/test_moler_test.py
=> Stpes end fix

moler/cmd/commandtextualgeneric.py, moler/cmd/unix/ctrl_c.py, test/unix/test_cmd_uptime.py, test/unix/test_cmd_whoami.py
=> ctrl+c functionality for unix

moler/cmd/commandtextualgeneric.py, moler/cmd/unix/ssh.py, moler/cmd/unix/telnet.py, test/test_moler_test.py, test/unix/test_cmd_chmod.py, test/unix/test_cmd_chown.py, test/unix/test_cmd_iperf.py, test/unix/test_cmd_mv.py, test/unix/test_cmd_scp.py, test/unix/test_cmd_sftp.py, test/unix/test_cmd_socat.py, test/unix/test_cmd_ssh.py, test/unix/test_cmd_su.py, test/unix/test_cmd_telnet.py, test/unix/test_cmd_top.py
Command should wait for prompt also when it fails.
=> Cmd wait for prompt on failure

moler/cmd/commandtextualgeneric.py, moler/cmd/unix/exit_telnet.py
Detect only beginning of command string to detect command start.
=> Start long commands

moler/device/textualdevice.py
Add parameter for_state to get_event and get_cmd methods of TextualDevice
=> Add parameter for_state to get_event and get_cmd methods of TextualDevice

moler/device/textualdevice.py, moler/device/unixlocal.py
=> 157 goto state print stacktrace on demand

moler/cmd/unix/ssh.py, moler/cmd/unix/sudo.py, moler/cmd/unix/telnet.py, moler/runner.py, test/unix/test_cmd_sudo.py
Break telnet or ssh command when remote host asks for password and commands does not have anymore. Do not wait for timeout.
=> Do not wait for timeout for command ssh or telnet when password fails.

moler/cmd/commandtextualgeneric.py, moler/cmd/unix/genericunix.py
Adds method _decode_line to CommandTextualGeneric
=> Adds method _decode_line to CommandTextualGeneric

moler/cmd/unix/scp.py, test/cmd/unix/test_cmd_scp.py
=> scp refactoring

README.md, docs/source/conf.py, setup.py
New package release - @emcek please check.
=> New release v0.13.0

README.md, docs/source/conf.py, setup.py
=> New release v0.14.0

moler/cmd/at/at.py, moler/cmd/commandchangingprompt.py, moler/cmd/commandtextualgeneric.py, moler/cmd/juniper_ex/genericjuniperex.py, moler/cmd/unix/exit.py, moler/cmd/unix/exit_telnet.py, moler/cmd/unix/generictelnetssh.py, moler/cmd/unix/ssh.py, moler/cmd/unix/su.py, moler/cmd/unix/telnet.py, moler/connection_observer.py
New generic class for commands they are changig prompt
=> New generic class for commands they are changig prompt

README.md, setup.py
=> New release v0.15.0

README.md, docs/source/conf.py, setup.py
@marcin-usielski  - please check :)
=> New release v0.15.1

README.md, docs/source/conf.py, setup.py
=> New release v1.0.0

.travis.yml, docs/source/conf.py, docs/source/moler.cmd.juniper.cli.rst, docs/source/moler.cmd.juniper.configure.rst, docs/source/moler.cmd.juniper.rst, docs/source/moler.cmd.juniper_ex.cli.rst, docs/source/moler.cmd.juniper_ex.configure.rst, docs/source/moler.cmd.juniper_ex.rst, docs/source/moler.cmd.rst, docs/source/moler.cmd.scpi.rst, docs/source/moler.cmd.scpi.scpi.rst, docs/source/moler.cmd.unix.rst, docs/source/moler.config.rst, docs/source/moler.device.rst, docs/source/moler.events.juniper.rst, docs/source/moler.events.juniper_ex.rst, docs/source/moler.events.rst, docs/source/moler.events.scpi.rst, docs/source/moler.events.shared.rst, docs/source/moler.events.unix.rst, docs/source/moler.io.asyncio.rst, docs/source/moler.io.raw.rst, docs/source/moler.io.rst, docs/source/moler.rst, docs/source/moler.util.rst
=> Add new sphinx files for docs geneartion

moler/cmd/unix/gzip.py, test/cmd/unix/test_cmd_gzip.py
Add gzip command class and tests.
=> Add gzip command

moler/cmd/unix/sudo.py
Setting result is not required for sudo command.
=> ret is not required for sudo

README.md, docs/source/conf.py, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.1.0

README.md, docs/source/conf.py, docs/source/moler.rst, setup.py
=> New release v1.2.0

moler/device/textualdevice.py, moler/event.py, test/test_event.py
Option to disable log every occurrence for events
=> option to disable log every occurrence for events

moler/config/__init__.py, test/device/test_device_configuration.py
Backward compatibility for load_device_from_config
=> Backward compatibility for load_device_from_config

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
@Ernold11  - please check 🏗 📦 🐛
=> New release v1.3.1

README.md, docs/source/conf.py, setup.py
=> New release v1.4.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.at.rst, setup.py
@marcin-usielski - please check 👌
=> New release v1.5.0

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
@marcin-usielski - please check 😃
=> New release v1.5.1

README.md, docs/source/moler.cmd.at.rst, docs/source/moler.cmd.unix.rst, docs/source/moler.device.rst, docs/source/moler.rst, docs/source/moler.util.rst
@marcin-usielski  - please check 👓 📦
=> New release v1.6.0

README.md, docs/source/moler.cmd.at.rst, docs/source/moler.cmd.juniper.configure.rst, docs/source/moler.cmd.juniper_ex.cli.rst, docs/source/moler.cmd.juniper_ex.configure.rst, docs/source/moler.cmd.juniper_ex.rst, docs/source/moler.cmd.rst, docs/source/moler.cmd.scpi.scpi.rst, docs/source/moler.cmd.unix.rst, docs/source/moler.device.rst, docs/source/moler.events.juniper.rst, docs/source/moler.events.juniper_ex.rst, docs/source/moler.events.scpi.rst, docs/source/moler.events.shared.rst, docs/source/moler.events.unix.rst, docs/source/moler.io.rst, docs/source/moler.parser.rst, docs/source/moler.rst, docs/source/moler.util.rst
@marcin-usielski - please check
=> New release v1.7.0

README.md, docs/source/moler.cmd.at.rst, docs/source/moler.cmd.juniper.configure.rst, docs/source/moler.cmd.juniper_ex.cli.rst, docs/source/moler.cmd.juniper_ex.configure.rst, docs/source/moler.cmd.juniper_ex.rst, docs/source/moler.cmd.scpi.scpi.rst, docs/source/moler.cmd.unix.rst, docs/source/moler.device.rst, docs/source/moler.events.juniper.rst, docs/source/moler.events.juniper_ex.rst, docs/source/moler.events.scpi.rst, docs/source/moler.events.shared.rst, docs/source/moler.events.unix.rst, docs/source/moler.io.rst, docs/source/moler.parser.rst, docs/source/moler.rst, docs/source/moler.util.rst
Please check @marcin-usielski @akubala
=> New release v1.8.0

README.md, docs/source/conf.py, setup.py
=> New release v1.9.0

README.md, docs/source/conf.py, docs/source/moler.rst, setup.py
=> New release v1.10.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.adb.rst, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.11.0

docs/source/conf.py
=> New release v1.12.0

README.md, docs/source/conf.py, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.13.0

CHANGELOG.md, README.md, docs/source/conf.py, moler/cmd/scpi/scpi/run_command.py, moler/cmd/unix/run_script.py, setup.py
=> New release v1.14.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.pdu_aten.pdu.rst, docs/source/moler.cmd.pdu_aten.rst, docs/source/moler.cmd.rst, docs/source/moler.device.rst, docs/source/moler.events.pdu_aten.rst, docs/source/moler.events.rst, setup.py
=> New release v1.15.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.17.0

moler/abstract_moler_connection.py, moler/device/device.py, moler/device/junipergeneric.py, moler/device/pdu_aten.py, moler/device/scpi.py, moler/device/textualdevice.py, moler/io/raw/tcp.py, test/conftest.py, test/device/test_device.py, test/device/test_device_configuration.py, test/test_connection_configuration.py, test/test_connection_factory.py
fixes:
- devices should pass io_constructor_kwargs down to base class
- better cleanup in tests for tests independence
=> Devices fixes

README.md, docs/source/conf.py, docs/source/moler.device.rst, docs/source/moler.io.raw.rst, setup.py
=> New release v1.19.0

README.md, examples/command/my_devices.yml, examples/command/unix_ps_on_device.py
=> fix packages for UnixLocal in examples

moler/cmd/commandtextualgeneric.py, moler/cmd/unix/tcpdump.py, moler/cmd/unix/unxz.py, moler/runner.py
Command tcpdump may break on specific regex.
=> Commands may break on regex

README.md, docs/source/conf.py, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.20.0

README.md, docs/source/conf.py, setup.py
=> New release v1.21.0

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> New release v1.22.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.23.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.24.0

moler/cmd/at/ati.py, moler/cmd/at/get_product_info.py
change ATI cmd name to GetProductInfo
=> change ATI cmd name to GetProductInfo

README.md, docs/source/conf.py, docs/source/moler.cmd.at.rst, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.25.0

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> New release v1.25.1

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> New release v1.26.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.at.rst, docs/source/moler.cmd.unix.rst, setup.py
=> New release v1.27.0

CHANGELOG.md, README.md, docs/source/conf.py, docs/source/moler.cmd.at.rst, setup.py
=> New release v1.28.0

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> New release v1.29.0

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> New release v1.30.0

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> Release v1.31.0

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> New release v1.31.1

moler/cmd/__init__.py, moler/cmd/commandtextualgeneric.py, test/test_helpers.py
Methods search_compiled and match_compiled can support None as compiled regex,
=> Methods search_compiled and match_compiled can support None as compiled regex

CHANGELOG.md, README.md, docs/source/conf.py, setup.py
=> Version 2.10.0

.github/workflows/ci.yaml, .travis.yml, docs/source/moler.cmd.at.rst, moler/cmd/at/get_cell_id.py, moler/cmd/at/get_cell_id_gprs.py, moler/cmd/at/get_cell_id_lte.py, moler/cmd/at/get_cell_id_nr.py, moler/cmd/at/set_cell_id.py, moler/cmd/at/set_cell_id_gprs.py, moler/cmd/at/set_cell_id_lte.py, moler/cmd/at/set_cell_id_nr.py
Add AT commands:
AT+CREG?
AT+CGREG?
AT+CEREG?
AT+C5GREG?
AT+CREG={}
AT+CGREG={}
AT+CEREG={}
AT+C5GREG={}
=> Implement at cmd for getting registered cell id information

CHANGELOG.md, moler/cmd/at/get_apns.py
Example of qualcomm sdx55 response (a bit anonymized)
```
AT+CGDCONT?
+CGDCONT: 1,"IPV4V6","apn1-ips-05","0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0",0,0,0,0,,,,,,,,,"",,,,0
OK
```
=> Change at command  to accept  in apn name

moler/cmd/at/gt_cell_lock.py
Adds a new command used for locking cell on AT devices with Qualcomm X55 chipsets
=> add new locking cell command for AT devices
